services:
  postgres:
    image: postgres:17
    container_name: sentineth-postgres
    restart: unless-stopped

    environment:
      POSTGRES_USER: sentineth
      POSTGRES_PASSWORD: sentineth_dev_password
      POSTGRES_DB: sentineth

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: