"""add document processing fields

Revision ID: 0a0b6a5ea51e
Revises: ceb4c8f5f751
Create Date: 2026-08-18 18:08:46.014893

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a0b6a5ea51e'
down_revision: Union[str, Sequence[str], None] = 'ceb4c8f5f751'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column(
        'documents',
        sa.Column(
            'status',
            sa.String(length=20),
            nullable=False,
            server_default='UPLOADED',
        ),
    )
    op.execute(
        "UPDATE documents SET status = 'UPLOADED' WHERE status IS NULL"
    )
    op.add_column(
        'documents',
        sa.Column(
            'content_hash',
            sa.String(length=64),
            nullable=True,
        ),
    )
    op.add_column(
        'documents',
        sa.Column(
            'error_message',
            sa.Text(),
            nullable=True,
        ),
    )
    op.alter_column(
        'documents',
        'status',
        server_default=None,
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'error_message')
    op.drop_column('documents', 'content_hash')
    op.drop_column('documents', 'status')
    # ### end Alembic commands ###
