"""add document processing fields

Revision ID: ceb4c8f5f751
Revises: c446472509e6
Create Date: 2026-08-18 18:06:32.480877

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ceb4c8f5f751'
down_revision: Union[str, Sequence[str], None] = 'c446472509e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """No-op.

    This revision was autogenerated empty and superseded by
    0a0b6a5ea51e, which actually adds the document processing
    columns (status, content_hash, error_message).

    It is retained as a no-op rather than deleted so that databases
    already stamped with this revision keep a valid upgrade path.
    """
    pass


def downgrade() -> None:
    """No-op. See upgrade()."""
    pass
